# Generated by Django 4.1.3 on 2023-02-13 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_rename_homework_homeworks_alter_homeworks_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichierPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('fileType', models.CharField(choices=[('PH', 'Langage php'), ('EN', 'English langage'), ('MA', 'MariaDB'), ('PY', 'Langage python'), ('JV', 'Java'), ('HCS', 'HTML and CSS'), ('CS', 'Csharp'), ('C', 'Langage C')], max_length=50)),
                ('course_file', models.FileField(upload_to='cours')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='serialNumber',
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_finished', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
