# Generated by Django 4.1.3 on 2023-02-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_fichierpdf_remove_student_serialnumber_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichierpdf',
            name='fileType',
            field=models.CharField(choices=[('PH', 'Langage php'), ('EN', 'English langage'), ('MA', 'Databases'), ('PY', 'Langage python'), ('JV', 'Java'), ('HCS', 'HTML and CSS'), ('XM', 'XML'), ('C', 'Langage C'), ('DJ', 'DJANGO')], max_length=50),
        ),
    ]
